"""user_products and shared_installations

Revision ID: 129af6a1bea3
Revises: 4182f9590ff9
Create Date: 2026-05-21 21:09:22.676440

"""
from alembic import op
import sqlalchemy as sa


revision = '129af6a1bea3'
down_revision = '4182f9590ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_installation_hospitals',
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['installation_id'], ['shared_installations.id'], ),
    sa.PrimaryKeyConstraint('installation_id', 'hospital_id')
    )
    op.create_table('user_products',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_products')
    op.drop_table('shared_installation_hospitals')
    op.drop_table('shared_installations')
    # ### end Alembic commands ###
