"""products_m2m_hospital_project_templates

Revision ID: 39b56e013c5e
Revises: f64882fe59f7
Create Date: 2026-05-21 20:13:25.540708

"""
from alembic import op
import sqlalchemy as sa


revision = '39b56e013c5e'
down_revision = 'f64882fe59f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_products',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('hospital_id', 'product_id')
    )
    op.create_table('project_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_template_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_priority', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Migrate existing hospital_id → hospital_products M2M rows
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, hospital_id FROM products WHERE hospital_id IS NOT NULL")).fetchall()
    if rows:
        conn.execute(
            sa.text("INSERT INTO hospital_products (hospital_id, product_id) VALUES (:h, :p) ON CONFLICT DO NOTHING"),
            [{"h": r[1], "p": r[0]} for r in rows],
        )

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_hospital_id_fkey'), type_='foreignkey')
        batch_op.drop_column('hospital_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('products_hospital_id_fkey'), 'hospitals', ['hospital_id'], ['id'])

    op.drop_table('project_template_tasks')
    op.drop_table('project_templates')
    op.drop_table('hospital_products')
    # ### end Alembic commands ###
