"""kb_articles_ticket_templates_sla

Revision ID: 4182f9590ff9
Revises: 39b56e013c5e
Create Date: 2026-05-21 20:29:58.739513

"""
from alembic import op
import sqlalchemy as sa


revision = '4182f9590ff9'
down_revision = '39b56e013c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('response_hours', sa.Float(), nullable=False),
    sa.Column('resolve_hours', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority')
    )
    op.create_table('kb_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_articles_slug'), ['slug'], unique=True)

    op.create_table('ticket_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('default_priority', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_response_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sla_response_due', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sla_resolve_due', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sla_breached', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('sla_breached')
        batch_op.drop_column('sla_resolve_due')
        batch_op.drop_column('sla_response_due')
        batch_op.drop_column('first_response_at')

    op.drop_table('ticket_templates')
    with op.batch_alter_table('kb_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_articles_slug'))

    op.drop_table('kb_articles')
    op.drop_table('sla_policies')
    # ### end Alembic commands ###
