"""ticket_statuses table

Revision ID: 689aed09d9c0
Revises: 129af6a1bea3
Create Date: 2026-05-21 21:32:03.875710

"""
from alembic import op
import sqlalchemy as sa


revision = '689aed09d9c0'
down_revision = '129af6a1bea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_statuses',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_statuses')
    # ### end Alembic commands ###
